export { HangoutsApiClient, type HangoutsApiClientOptions } from './api-client.js';
export {
  loginWithKeychain,
  loginWithSignFn,
  loginWithAioha,
  isKeychainAvailable,
  type AiohaLike,
} from './keychain-auth.js';
export { HangoutsApiError } from './errors.js';
export type {
  Room,
  RoomVisibility,
  BoostConfig,
  BoostEvent,
  BoostRejectReason,
  CreateRoomResponse,
  JoinRoomResponse,
  AuthSession,
  ChallengeResponse,
  ParticipantRole,
  HandRaiseEvent,
  DataMessage,
  RecordingMode,
  RecordingLayout,
  RecordingStartResponse,
  RecordingStopResponse,
  RecordingStatusResponse,
  RecordingLayoutResponse,
  RecordingUploadResponse,
  RecordingFileResult,
  StreamPlatform,
  StreamStartResponse,
  StreamStopResponse,
  StreamStatusResponse,
  EventStatus,
  EventVisibility,
  HangoutsEvent,
  CreateEventInput,
  UpdateEventInput,
  UserPresence,
  StartEventResponse,
} from './types.js';
