export { HangoutsApiClient, type HangoutsApiClientOptions } from './api-client.js';
export {
  loginWithKeychain,
  loginWithSignFn,
  loginWithAioha,
  isKeychainAvailable,
  type AiohaLike,
} from './keychain-auth.js';
export { HangoutsApiError } from './errors.js';
export { buildLichessAnalysisUrl } from './chess-utils.js';
export { formatWordGuessRecap } from './word-guess-utils.js';
export { formatFastDrawRecap } from './fast-draw-utils.js';
export type {
  Room,
  RoomVisibility,
  BoostConfig,
  BoostEvent,
  BoostRejectReason,
  CreateRoomResponse,
  JoinRoomResponse,
  AuthSession,
  ChallengeResponse,
  ParticipantRole,
  HandRaiseEvent,
  DataMessage,
  RecordingMode,
  RecordingLayout,
  RecordingStartResponse,
  RecordingStopResponse,
  RecordingStatusResponse,
  RecordingLayoutResponse,
  RecordingUploadResponse,
  RecordingFileResult,
  StreamPlatform,
  StreamStartResponse,
  StreamStopResponse,
  StreamStatusResponse,
  EventStatus,
  EventVisibility,
  HangoutsEvent,
  CreateEventInput,
  UpdateEventInput,
  UserPresence,
  StartEventResponse,
  GameInfo,
  ActiveGame,
  GameStartResponse,
  GameActionResponse,
  GameMessage,
  GameResultPayload,
  ChessGameResult,
  FastDrawGameResult,
  WordGuessLeaderboardEntry,
  WordGuessGameResult,
  WordCollection,
} from './types.js';
